/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budget;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author karmi
 */
public class mainSc extends javax.swing.JFrame {

    public String itemName;
    public float itemPrice, totPrice = 0;
    public String[] itemList = new String[1000], lines = new String[10000];
    public float[] priceList = new float[1000];
    public int i = -1, j = -1;
    public String line = "", ledger = "";

    /**
     * Creates new form mainSc
     */
    public mainSc() {
        initComponents();
        startup();
        changeTitle();
    }

    public void startup() {
        panEntry.setVisible(true);
        panSum.setVisible(false);
    }

    public void changeTitle() {
        DateFormat df = new SimpleDateFormat("MM");
        Date d = new Date();
        String cMonth = df.format(d);
        txtTitle.setText(getMonth(cMonth));
    }

    public String getMonth(String cM) {

        switch (cM) {
            case "01":
                cM = "January Budget";
                break;
            case "02":
                cM = "February Budget";
                break;
            case "03":
                cM = "March Budget";
                break;
            case "04":
                cM = "April Budget";
                break;
            case "05":
                cM = "May Budget";
                break;
            case "06":
                cM = "June Budget";
                break;
            case "07":
                cM = "July Budget";
                break;
            case "08":
                cM = "August Budget";
                break;
            case "09":
                cM = "September Budget";
                break;
            case "10":
                cM = "October Budget";
                break;
            case "11":
                cM = "November Budget";
                break;
            case "12":
                cM = "December Budget";
                break;
            default:
                cM = "NULL";
        }

        return cM;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEntry = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        panInputs1 = new javax.swing.JPanel();
        lblItem1 = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMS = new javax.swing.JButton();
        panSum = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisp = new javax.swing.JTextArea();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("Budget");

        lblItem1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblItem1.setText("Item Name:");

        lblPrice1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPrice1.setText("Item Price:");

        txtItem.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemKeyPressed(evt);
            }
        });

        txtPrice.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panInputs1Layout = new javax.swing.GroupLayout(panInputs1);
        panInputs1.setLayout(panInputs1Layout);
        panInputs1Layout.setHorizontalGroup(
            panInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInputs1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panInputs1Layout.createSequentialGroup()
                        .addGroup(panInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtItem)
                            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panInputs1Layout.setVerticalGroup(
            panInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInputs1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItem1)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panInputs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice1)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnExit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExitKeyPressed(evt);
            }
        });

        btnMS.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnMS.setText("Monthly Summary");
        btnMS.setEnabled(false);
        btnMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMSMouseClicked(evt);
            }
        });
        btnMS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMSKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panEntryLayout = new javax.swing.GroupLayout(panEntry);
        panEntry.setLayout(panEntryLayout);
        panEntryLayout.setHorizontalGroup(
            panEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panInputs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEntryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addComponent(btnMS, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panEntryLayout.setVerticalGroup(
            panEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEntryLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panInputs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        getContentPane().add(panEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 480, -1));

        txtDisp.setColumns(50);
        txtDisp.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtDisp.setRows(5);
        txtDisp.setEnabled(false);
        jScrollPane1.setViewportView(txtDisp);

        btnback.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnback.setText("BACK");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panSumLayout = new javax.swing.GroupLayout(panSum);
        panSum.setLayout(panSumLayout);
        panSumLayout.setHorizontalGroup(
            panSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addContainerGap())
        );
        panSumLayout.setVerticalGroup(
            panSumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        addItem();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyPressed
        keyCheck(evt);
    }//GEN-LAST:event_btnExitKeyPressed

    private void txtItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemKeyPressed
        keyCheck(evt);
    }//GEN-LAST:event_txtItemKeyPressed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        keyCheck(evt);
    }//GEN-LAST:event_txtPriceKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        keyCheck(evt);
    }//GEN-LAST:event_formKeyPressed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        keyCheck(evt);
    }//GEN-LAST:event_btnAddKeyPressed

    private void btnMSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMSKeyPressed
        keyCheck(evt);
    }//GEN-LAST:event_btnMSKeyPressed

    private void btnMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMSMouseClicked
        panEntry.setVisible(false);
        panSum.setVisible(true);

        try {
            fWrite(ledger);
        } catch (IOException ex) {
            Logger.getLogger(mainSc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMSMouseClicked

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        panSum.setVisible(false);
        panEntry.setVisible(true);
    }//GEN-LAST:event_btnbackMouseClicked

    public void keyCheck(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtItem.grabFocus();
            addItem();
        }
    }

    public void addItem() {

        i++;

        if (txtItem.getText().isEmpty()) {
            itemName = " -- ";
        } else {
            itemName = txtItem.getText();
        }

        if (txtPrice.getText().isEmpty()) {
            itemPrice = (float) 0;
        } else {
            itemPrice = Float.parseFloat(txtPrice.getText());
        }

        itemList[i] = itemName;
        priceList[i] = itemPrice;
        totPrice += itemPrice;

        line = itemName + "\t-----> $" + itemPrice;
        ledger = ledger + line + "\n";

        txtItem.setText(null);
        txtPrice.setText(null);
        btnMS.setEnabled(true);
    }

    public void fWrite(String ledger) throws IOException {

        txtDisp.setText(ledger);

        DateFormat df = new SimpleDateFormat("yyyyMMdd");
        Date d = new Date();
        String date = df.format(d), fileName = date + ".txt";

        File f = new File(fileName);
        FileWriter fw = new FileWriter(fileName);
        fw.write(ledger);
        fw.close();

        Scanner fScan = new Scanner(f);

        while (fScan.hasNextLine()) {
            j++;
            String line = fScan.nextLine();
            lines[j] = line;
            System.out.println(line);
        }

        for (int x = 0; x <= j; x++) {
            String[] words = lines[x].split("----->");
            System.out.println(words[0] + " " + words[1]);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainSc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainSc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainSc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainSc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainSc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMS;
    private javax.swing.JButton btnback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JPanel panEntry;
    private javax.swing.JPanel panInputs1;
    private javax.swing.JPanel panSum;
    private javax.swing.JTextArea txtDisp;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
